# Robbie Voice Satellite - ESPHome config for ReSpeaker Lite (XIAO ESP32-S3)
#
# Based on Seeed Studio wiki and formatBCE integration:
#   https://wiki.seeedstudio.com/respeaker_lite_ha/
#   https://github.com/formatBCE/Respeaker-Lite-ESPHome-integration
#
# Flash with: esphome run robbie_voice_satellite.yaml

esphome:
  name: robbie-voice
  friendly_name: "Robbie Voice Satellite"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  logs:
    micro_wake_word: DEBUG
    voice_assistant: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.0.25
    gateway: 10.0.0.138
    subnet: 255.255.255.0
  power_save_mode: NONE

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

mdns:
  disabled: true

ota:
  - platform: esphome

# --- I2S Audio ---
# ReSpeaker Lite has XMOS XU316 DSP connected via I2S at 48kHz

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO7
    i2s_bclk_pin: GPIO8

microphone:
  - platform: i2s_audio
    id: i2s_mics
    i2s_audio_id: i2s_audio_bus
    adc_type: external
    i2s_din_pin: GPIO44
    sample_rate: 16000
    bits_per_sample: 16bit

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    i2s_audio_id: i2s_audio_bus
    dac_type: external
    i2s_dout_pin: GPIO43
    sample_rate: 16000

# --- Wake Word ---

micro_wake_word:
  id: mww
  microphone:
    microphone: i2s_mics
    channels: 0
  models:
    - model: okay_nabu
  on_wake_word_detected:
    - light.turn_on:
        id: status_led
        red: 0%
        green: 0%
        blue: 100%
        effect: "listening_pulse"

# --- Voice Assistant Pipeline ---

voice_assistant:
  id: va
  microphone:
    microphone: i2s_mics
    channels: 0
  speaker: i2s_speaker
  micro_wake_word: mww
  use_wake_word: true
  noise_suppression_level: 0
  auto_gain: 0 dBFS
  volume_multiplier: 2.0

  on_start:
    - light.turn_on:
        id: status_led
        red: 0%
        green: 0%
        blue: 100%
        effect: "listening_pulse"

  on_tts_end:
    - light.turn_off:
        id: status_led

  on_error:
    - light.turn_on:
        id: status_led
        red: 100%
        green: 0%
        blue: 0%
    - delay: 2s
    - light.turn_off:
        id: status_led

  on_end:
    - light.turn_off:
        id: status_led

# --- Status LED ---

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    pin: GPIO1
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    name: "Status LED"
    effects:
      - pulse:
          name: "listening_pulse"
          transition_length: 300ms
          update_interval: 300ms
          min_brightness: 20%
          max_brightness: 100%
